#pragma once

#define GOOMBA_WALK_SPEED		0.07f;
#define GOOMBA_BBOX_SIZE		48
#define GOOMBA_BBOX_HEIGHT_DIE	27
#define GOOMBA_DIE_Y			21
#define GOOMBA_STATE_WALK		100
#define GOOMBA_STATE_DIE		200
#define GOOMBA_DEATH_TIME		250
#define GOOMBA_STATE_FLY		251

#define RG_STATE_WALK			100
#define RG_STATE_DIE			200
#define RG_STATE_JUMP			300
#define RG_JUMP_HEIGHT			50
#define RG_BBOX_HEIGHT_DIE		27
#define RG_BBOX_SIZE			48
#define RG_WALK_SPEED			0.07f
#define RG_WALK_TIME			500
#define RG_JUMP_PUSH			0.332f

#define KOOPAS_WALK_SPEED		0.15f
#define KOOPAS_SHELL_SPEED		0.67f

#define KOOPAS_SIZE				48
#define KOOPAS_WIDTH			50
#define KOOPAS_HEIGHT			48
#define KOOPAS_SHELL_SIZE		48

#define KOOPAS_BBOX_HEIGHT		50
#define KOOPAS_BBOX_HEIGHT_DIE	16
#define KOOPAS_STATE_WALK		100
#define KOOPAS_STATE_DIE		200
#define KOOPAS_STATE_JUMP		300

#define KOOPAS_CROUCH_TIME		7000
#define KOOPAS_JUMP_HEIGHT		90
#define KOOPAS_WALK_TIME		100
#define KOOPAS_RESPAWN_TIME		7000
#define KOOPAS_DEATH_TIME		5000

#define ENEMIES_GRAVITY			0.0016f
