#pragma once

#define PM_MAX							1
#define PM_INCREASE						0.008f
#define PM_DECREASE						0.0016f

#define MARIO_WALK_SPEED				0.27f
#define MARIO_RUN_SPEED					0.48f
#define MARIO_FLY_SPEED_X				0.27f
#define MARIO_FLOAT_SPEED_X				0.20f

#define MARIO_RUN_ACCELERATION			0.0005613f
#define MARIO_WALK_ACCELERATION			0.000476f
#define MARIO_SKID_ACCELERATION			0.001104f

#define MARIO_JUMP_FALL_POINT			80
#define MARIO_BEGIN_HIGH_JUMP_HEIGHT	97
#define MARIO_HIGH_JUMP_FALL_POINT		216
#define MARIO_FLY_FALL_POINT			300
#define MARIO_FLY_MAX_POINT				1000

#define MARIO_WALK_FRICTION				0.0014306f
#define MARIO_RUN_FRICTION				0.0016366f
#define MARIO_CROUCH_FRICTION 			0.0008766f

#define MARIO_GRAVITY				0.002f

#define MARIO_JUMP_PUSH				0.432f
#define MARIO_FLY_PUSH				0.632f
#define MARIO_JUMP_DEFLECT_SPEED	0.2f
#define MARIO_DIE_DEFLECT_SPEED		0.5f

#define MARIO_STATE_IDLE			10
#define MARIO_STATE_WALK			100
#define MARIO_STATE_RUN				200
#define MARIO_STATE_RUN_HIGH_SPEED	300

#define MARIO_STATE_DIE				400
#define MARIO_STATE_CROUCH			500

#define MARIO_STATE_JUMP			600
#define MARIO_STATE_JUMP_IDLE		700
#define MARIO_STATE_JUMP_HIGH		800
#define MARIO_STATE_JUMP_FALL		900

#define MARIO_STATE_FLY				2000
#define MARIO_STATE_FLOAT			2001

#define MARIO_STATE_ATTACK			1001
#define MARIO_STATE_FIRE			1002


#define	MARIO_LEVEL_SMALL	1
#define	MARIO_LEVEL_BIG		2

#define MARIO_BIG_BBOX_WIDTH	45
#define MARIO_BIG_BBOX_HEIGHT	81

#define MARIO_CROUCH_SUBSTRACT	 26

#define MARIO_SMALL_BBOX_WIDTH  13
#define MARIO_SMALL_BBOX_HEIGHT 15

#define MARIO_UNTOUCHABLE_TIME		5000
#define MARIO_ATTACK_TIME			350
#define MARIO_FIRE_TIME				100

#define MARIO_FLY_TIME				500
#define MARIO_FLOAT_TIME			500
